### ISSUE TITLE
Numpy read-only error in to_xarray method of grid.py

### ISSUE THREAD

**Issue by wolfidan** [MeteoSwiss/pyart#13]
When trying to run a very simple example:

    f = '/scratch/wolfensb/RZC222962355VL.801'
    f = pyart.aux_io.read_cartesian_metranet(f)
    
    display = pyart.graph.GridMapDisplay(f)
    display.plot_grid('radar_estimated_rain_rate', level=0)

I get the following error

Traceback (most recent call last):
  File "test_pyart_norm_issue.py", line 8, in <module>
    display.plot_grid('radar_estimated_rain_rate', level=0)
  File "/store/msrad/utils/anaconda3-wolfensb/envs/rainforest_tests/lib/python3.8/site-packages/pyart_mch-1.4.5-py3.8-linux-x86_64.egg/pyart/graph/gridmapdisplay.py", line 180, in plot_grid
    ds = self.grid.to_xarray()
  File "/store/msrad/utils/anaconda3-wolfensb/envs/rainforest_tests/lib/python3.8/site-packages/pyart_mch-1.4.5-py3.8-linux-x86_64.egg/pyart/core/grid.py", line 328, in to_xarray
    data = xarray.DataArray(np.ma.expand_dims(field_data, 0),
  File "/store/msrad/utils/anaconda3-wolfensb/envs/rainforest_tests/lib/python3.8/site-packages/xarray-2022.10.0-py3.8.egg/xarray/core/dataarray.py", line 414, in __init__
    data = as_compatible_data(data)
  File "/store/msrad/utils/anaconda3-wolfensb/envs/rainforest_tests/lib/python3.8/site-packages/xarray-2022.10.0-py3.8.egg/xarray/core/variable.py", line 234, in as_compatible_data
    data[mask] = fill_value
ValueError: assignment destination is read-only

**Comment by wolfidan** [comment]
This was solved in commit 318e2c0e035c0ae6c6cd25715e9fc6455801baaf

It’s an error when converting from masked to normal numpy array in the xarray conversion. I guess it happens on some numpy versions only
I found a fix for it: add field_data.setflags(write=1)
At line 327 in grid.py.
